merge INTO MPA_RATINGS KEY (ID) VALUES (1, 'G');
merge INTO MPA_RATINGS KEY (ID) VALUES (2, 'PG');
merge INTO MPA_RATINGS KEY (ID) VALUES (3, 'PG-13');
merge INTO MPA_RATINGS KEY (ID) VALUES (4, 'R');
merge INTO MPA_RATINGS KEY (ID) VALUES (5, 'NC-17');

merge INTO GENRES KEY (ID) VALUES (1, 'COMEDY');
merge INTO GENRES KEY (ID) VALUES (2, 'DRAMA');
merge INTO GENRES KEY (ID) VALUES (3, 'CARTOON');
merge INTO GENRES KEY (ID) VALUES (4, 'THRILLER');
merge INTO GENRES KEY (ID) VALUES (5, 'DOCUMENTARY');
merge INTO GENRES KEY (ID) VALUES (6, 'ACTION');
