create table if not exists GENRES
(
    ID   INTEGER
        primary key,
    NAME CHARACTER VARYING(31) not null
);

create table if not exists MPA_RATINGS
(
    ID   INTEGER
        primary key,
    NAME CHARACTER VARYING(16) not null
);

create table if not exists FILMS
(
    ID            INTEGER generated by default as identity
        primary key,
    NAME          CHARACTER VARYING(160) not null,
    DESCRIPTION   CHARACTER VARYING,
    RELEASE_DATE  DATE,
    DURATION      INTEGER,
    MPA_RATING_ID INTEGER
        references MPA_RATINGS
);

create table if not exists FILMS_GENRES
(
    FILM_ID  INTEGER not null
        references FILMS,
    GENRE_ID INTEGER not null
        references GENRES,
    primary key (FILM_ID, GENRE_ID)
);

create table if not exists USERS
(
    ID       INTEGER generated by default as identity (start with 1)
        primary key,
    LOGIN    CHARACTER VARYING(63) not null,
    EMAIL    CHARACTER VARYING(63) not null,
    NAME     CHARACTER VARYING(63),
    BIRTHDAY DATE
);

create table if not exists FRIENDS
(
    USER_ID   INTEGER not null
        references USERS,
    FRIEND_ID INTEGER not null
        references USERS,
    primary key (USER_ID, FRIEND_ID),
    CONSTRAINT NOT_EQUAL CHECK (USER_ID != FRIENDS.FRIEND_ID)

);

create table if not exists USERS_FILMS_LIKES
(
    USER_ID INTEGER not null
        references USERS,
    FILM_ID INTEGER not null
        references FILMS,
    primary key (FILM_ID, USER_ID)
);
